### ISSUE TITLE
Compile to html for use with Riot.js

### ISSUE THREAD

**Issue by brauliobo** [zohararad/jader#8]
I would like to `.js.tag.jade` files to be compiled to html so that I could use it with Riot as described at http://riotjs.com/guide/compiler/#pre-processors

How could that be done? Maybe a `.html.jade` sprockets processor?

**Comment by zohararad** [comment]
Hmm... this is not the use case for Jader, which compiles Jade files to JST Javascript functions.
You might want to copy the logic though somehow
